version: 2.1

jobs:
  one:    
    docker:
      - image: cimg/ruby:2.6.8
        auth:
          username: mayur2345
          password: kylo@6996
    steps:
      - checkout
      - run: echo "A first hello"
      - run: sleep 25
  two:
    docker:
      - image: cimg/ruby:3.0.2
      - auth:
        username: mayur2345
        password: kylo@6996
    steps:
      - checkout
      - run: echo "A more familiar hi"
      - run: sleep 15
      
workflows:
  one_and_two:
    jobs:
      - one
      - two
